# cspell:words asyncio pyright pylint pytest setuptools

[build-system]
requires = [ "setuptools >= 64" ]
build-backend = "setuptools.build_meta"

[project]
name = "automation-scripts"
version = "1.0.0+development"
description = "Automation scripts for the local project"
requires-python = ">= 3.11"

dependencies = [
    "benjaminhamon-standard-extensions[all] ~= 1.0.1",
    "bhamon-development-toolkit[python] ~= 3.1.1",
    "mockito ~= 1.5.4",
    "pyright ~= 1.1.404",
]

[project.scripts]
automation = "automation_scripts.run_command:main"
